version: 2

name: Dart CI

on: [push]

workflows:
    version: 2

    my_workflows:
    
    jobs:
       build:

        runs-on: ubuntu-latest

        container:
            image:  google/dart:latest

        steps:
        - uses: actions/checkout@v1
        - name: Install dependencies
        run: pub get
        - name: Run tests
        run: pub run test